export const CLAIM_REPOSITORY = "CLAIM_REPOSITORY";
export const CLAIM_DOCUMENT_REPOSITORY = "CLAIM_DOCUMENT_REPOSITORY";
export const STORAGE_REPOSITORY = "STORAGE_REPOSITORY";
export const AI_SUMMARY_REPOSITORY = "AI_SUMMARY_REPOSITORY";
