ALTER TABLE service_catalog
  ADD COLUMN IF NOT EXISTS apiBaseUrl VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS endpointsEnabled TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS humanHandoffEnabled TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS fileStorageEnabled TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS documentProcessingEnabled TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ocrEnabled TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS semanticSearchEnabled TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS jiraEnabled TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS jiraProjectKey VARCHAR(32) NULL,
  ADD COLUMN IF NOT EXISTS jiraDefaultIssueType VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS jiraAllowUserPriorityOverride TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS jiraAutoLabelWithServiceName TINYINT(1) NOT NULL DEFAULT 1;
