ALTER TABLE tenant_invoices
  ADD COLUMN IF NOT EXISTS taxRate DECIMAL(5,4) NULL,
  ADD COLUMN IF NOT EXISTS taxEur DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS stripeInvoiceId VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS stripePaymentIntentId VARCHAR(64) NULL;
