CREATE TABLE IF NOT EXISTS tenant_service_email_accounts (
  id VARCHAR(36) NOT NULL,
  tenantId VARCHAR(36) NOT NULL,
  serviceCode VARCHAR(64) NOT NULL,
  label VARCHAR(120) NULL,
  email VARCHAR(255) NOT NULL,
  provider VARCHAR(32) NOT NULL,
  host VARCHAR(255) NOT NULL,
  port INT NULL,
  username VARCHAR(255) NOT NULL,
  encryptedPassword TEXT NULL,
  folder VARCHAR(120) NULL,
  useSsl TINYINT(1) NOT NULL DEFAULT 1,
  useStartTls TINYINT(1) NOT NULL DEFAULT 0,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  lastUid BIGINT NULL,
  lastSyncAt TIMESTAMP NULL,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_tenant_service_email_accounts (tenantId, serviceCode, email),
  INDEX idx_tenant_service_email_accounts_tenant (tenantId),
  INDEX idx_tenant_service_email_accounts_service (serviceCode)
);
