CREATE TABLE tenant_service_files (
  id VARCHAR(36) NOT NULL,
  tenantId VARCHAR(36) NOT NULL,
  serviceCode VARCHAR(64) NOT NULL,
  conversationId VARCHAR(36) NULL,
  originalName VARCHAR(255) NOT NULL,
  contentType VARCHAR(255) NULL,
  sizeBytes BIGINT NOT NULL DEFAULT 0,
  storageProvider VARCHAR(64) NOT NULL,
  storageKey VARCHAR(255) NOT NULL,
  storageUrl VARCHAR(1024) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'uploaded',
  ocrStatus VARCHAR(32) NOT NULL DEFAULT 'pending',
  semanticStatus VARCHAR(32) NOT NULL DEFAULT 'pending',
  embeddingStatus VARCHAR(32) NOT NULL DEFAULT 'pending',
  embeddingModel VARCHAR(64) NULL,
  embeddingCount INT NULL,
  documentDomain VARCHAR(120) NULL,
  ocrDocumentId VARCHAR(36) NULL,
  resultType VARCHAR(32) NULL,
  resultContent TEXT NULL,
  resultFileUrl VARCHAR(1024) NULL,
  resultFileKey VARCHAR(255) NULL,
  errorMessage TEXT NULL,
  metadata JSON NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tenant_service (tenantId, serviceCode),
  KEY idx_tenant_conversation (tenantId, conversationId)
);
