INSERT INTO service_catalog (
  id,
  code,
  name,
  description,
  apiBaseUrl,
  endpointsEnabled,
  humanHandoffEnabled,
  fileStorageEnabled,
  documentProcessingEnabled,
  ocrEnabled,
  semanticSearchEnabled,
  emailAutomationEnabled,
  jiraEnabled,
  jiraProjectKey,
  jiraDefaultIssueType,
  jiraAllowUserPriorityOverride,
  jiraAutoLabelWithServiceName,
  priceMonthlyEur,
  priceAnnualEur,
  enabled,
  createdAt,
  updatedAt
)
SELECT
  UUID(),
  'asistente-renta',
  'Asistente IA para Declaracion de la Renta (ES)',
  'Asistente basado en IA para guiar la declaracion de la renta en Espana. Recoge datos generales, organiza ingresos y deducciones, propone checklist de documentos y genera un borrador explicativo sin valor legal. No accede a datos sensibles ni sustituye a un asesor fiscal.',
  NULL,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  NULL,
  NULL,
  true,
  true,
  69.00,
  690.00,
  true,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM service_catalog WHERE code = 'asistente-renta'
);
