INSERT INTO service_catalog (
  id,
  code,
  name,
  description,
  apiBaseUrl,
  endpointsEnabled,
  humanHandoffEnabled,
  fileStorageEnabled,
  documentProcessingEnabled,
  ocrEnabled,
  semanticSearchEnabled,
  emailAutomationEnabled,
  jiraEnabled,
  jiraProjectKey,
  jiraDefaultIssueType,
  jiraAllowUserPriorityOverride,
  jiraAutoLabelWithServiceName,
  priceMonthlyEur,
  priceAnnualEur,
  enabled,
  createdAt,
  updatedAt
)
SELECT
  UUID(),
  'clinicflow',
  'ClinicFlow AI',
  'Asistente omnicanal para clínicas dentales. Gestiona FAQ, agenda, triaje y borradores de informe con guardrails clínicos y cumplimiento RGPD.',
  NULL,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  NULL,
  NULL,
  1,
  1,
  149.00,
  1490.00,
  1,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM service_catalog WHERE code = 'clinicflow'
);
