INSERT INTO service_catalog (
  id,
  code,
  name,
  description,
  apiBaseUrl,
  endpointsEnabled,
  humanHandoffEnabled,
  fileStorageEnabled,
  documentProcessingEnabled,
  ocrEnabled,
  semanticSearchEnabled,
  emailAutomationEnabled,
  jiraEnabled,
  jiraProjectKey,
  jiraDefaultIssueType,
  jiraAllowUserPriorityOverride,
  jiraAutoLabelWithServiceName,
  priceMonthlyEur,
  priceAnnualEur,
  enabled,
  createdAt,
  updatedAt
)
SELECT
  UUID(),
  'simulador-financiero',
  'Simulador Inteligente de Productos Financieros',
  'Herramienta digital basada en IA que permite analizar, comparar y comprender productos financieros (préstamos, hipotecas o planes de ahorro) mediante simulaciones personalizadas y explicaciones claras. No requiere datos bancarios sensibles.',
  NULL,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  NULL,
  NULL,
  true,
  true,
  0.00,
  0.00,
  true,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM service_catalog WHERE code = 'simulador-financiero'
);
