INSERT INTO service_catalog (
  id,
  code,
  name,
  description,
  apiBaseUrl,
  priceMonthlyEur,
  priceAnnualEur,
  enabled,
  endpointsEnabled,
  humanHandoffEnabled,
  fileStorageEnabled,
  documentProcessingEnabled,
  ocrEnabled,
  semanticSearchEnabled,
  emailAutomationEnabled,
  jiraEnabled,
  jiraProjectKey,
  jiraDefaultIssueType,
  jiraAllowUserPriorityOverride,
  jiraAutoLabelWithServiceName,
  createdAt,
  updatedAt
)
SELECT
  UUID(),
  'email-automation',
  'Automatización Inteligente de Correos y Tickets',
  'Sistema basado en IA que lee correos entrantes, detecta intención, extrae datos clave y dispara acciones operativas (por ejemplo, creación de tickets en Jira).',
  NULL,
  199.00,
  1990.00,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  'OPS',
  'Task',
  1,
  1,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM service_catalog WHERE code = 'email-automation'
);
