import { useEffect, useMemo, useState } from "react";
import { DayPicker, type DateRange } from "react-day-picker";
import "react-day-picker/dist/style.css";

import { weekdayOptions } from "./constants/weekdayOptions";
import { toDateKey, formatDate, formatTime } from "./helpers/dateHelpers";
import {
  formatSlotLabel,
  formatSlotPatient,
  formatSlotStatus,
} from "./helpers/slotHelpers";
import { staffApi } from "../../../../infrastructure/api/clinicflowApi";
import {
  infoModals,
  type InfoModalKey,
} from "../../../../core/domain/infoModals";
import { SectionHeader } from "../../components/SectionHeader";
import { IconInfo, IconDelete } from "../../components/shared/icons";
import { Modal } from "../../components/shared/Modal";
import { Calendar } from "./Calendar";

export const AgendaPage = () => {
  const today = new Date();
  const rangeStart = new Date(today.getFullYear(), today.getMonth(), 1);
  const rangeEnd = new Date(today.getFullYear(), today.getMonth() + 3, 0);

  // ===== UI state =====
  const [dateFilter, setDateFilter] = useState(""); // YYYY-MM-DD
  const [selectedRange, setSelectedRange] = useState<DateRange | undefined>();
  const [activeInfoKey, setActiveInfoKey] = useState<InfoModalKey | null>(null);

  // ===== data state =====
  const [availability, setAvailability] = useState<any[]>([]);
  const [timeOff, setTimeOff] = useState<any[]>([]);
  const [holidays, setHolidays] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(false);

  // ===== forms =====
  const [windowForm, setWindowForm] = useState({
    startDate: toDateKey(rangeStart), // YYYY-MM-DD
    endDate: toDateKey(rangeEnd), // YYYY-MM-DD
    startTime: "09:00",
    endTime: "19:00",
    slotMinutes: 30,
    weekdays: [1, 2, 3, 4, 5],
    practitionerName: "",
    serviceCode: "",
  });

  const [slotForm, setSlotForm] = useState({
    startAt: "",
    endAt: "",
    durationMin: 30,
    practitionerName: "",
    serviceCode: "",
  });

  const [blockForm, setBlockForm] = useState({
    startTime: "",
    endTime: "",
    reason: "",
  });

  const [holidayForm, setHolidayForm] = useState({
    date: "",
    name: "",
  });

  useEffect(() => {
    if (!slotForm.startAt || !slotForm.durationMin) return;
    const start = new Date(slotForm.startAt);
    if (Number.isNaN(start.getTime())) return;
    const end = new Date(start);
    end.setMinutes(end.getMinutes() + Number(slotForm.durationMin));
    const iso = end.toISOString().slice(0, 16);
    if (iso !== slotForm.endAt) {
      setSlotForm((prev) => ({ ...prev, endAt: iso }));
    }
  }, [slotForm.startAt, slotForm.durationMin]);

  // ===== loaders =====
  const loadAvailability = async () => {
    setLoading(true);
    try {
      // IMPORTANTE:
      // Si tu API espera YYYY-MM-DD, pásale esto.
      // Si tu API espera ISO completo, aquí habría que volver a toISOString().
      const from = toDateKey(rangeStart);
      const to = toDateKey(rangeEnd);

      const data = await staffApi.listAvailability(from, to);
      const list = Array.isArray(data) ? data : [];

      // Autogenerar si no hay huecos:
      // (mantengo tu lógica original)
      if (!autoGenerated && list.length === 0) {
        setAutoGenerated(true);

        await staffApi.openAvailabilityWindow({
          startDate: from,
          endDate: to,
          startTime: windowForm.startTime,
          endTime: windowForm.endTime,
          weekdays: [1, 2, 3, 4, 5, 6, 7],
        });

        const refreshed = await staffApi.listAvailability(from, to);
        setAvailability(Array.isArray(refreshed) ? refreshed : []);
      } else {
        setAvailability(list);
      }

      setError(null);
    } catch (err: any) {
      setError(err?.message || "No se pudo cargar la disponibilidad.");
    } finally {
      setLoading(false);
    }
  };

  const loadTimeOff = async () => {
    try {
      const data = await staffApi.listTimeOff(
        toDateKey(rangeStart),
        toDateKey(rangeEnd),
      );
      setTimeOff(Array.isArray(data) ? data : []);
    } catch (err: any) {
      setError(err?.message || "No se pudo cargar los bloqueos.");
    }
  };

  const loadHolidays = async () => {
    try {
      const data = await staffApi.listHolidays(
        toDateKey(rangeStart),
        toDateKey(rangeEnd),
      );
      setHolidays(Array.isArray(data) ? data : []);
    } catch (err: any) {
      setError(err?.message || "No se pudo cargar festivos.");
    }
  };

  useEffect(() => {
    loadAvailability();
    loadTimeOff();
    loadHolidays();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ===== actions =====
  const toggleWeekday = (value: number) => {
    setWindowForm((prev) => {
      const exists = prev.weekdays.includes(value);
      const weekdays = exists
        ? prev.weekdays.filter((day) => day !== value)
        : [...prev.weekdays, value];
      return { ...prev, weekdays };
    });
  };

  const handleOpenWindow = async () => {
    if (!windowForm.startDate || !windowForm.endDate) {
      setError("Indica el rango de fechas.");
      return;
    }

    await staffApi.openAvailabilityWindow({
      startDate: windowForm.startDate,
      endDate: windowForm.endDate,
      startTime: windowForm.startTime,
      endTime: windowForm.endTime,
      slotMinutes: windowForm.slotMinutes,
      weekdays: windowForm.weekdays,
      practitionerName: windowForm.practitionerName || undefined,
      serviceCode: windowForm.serviceCode || undefined,
    });

    await loadAvailability();
  };

  const handleGenerateDefault = async () => {
    await staffApi.openAvailabilityWindow({
      startDate: toDateKey(rangeStart),
      endDate: toDateKey(rangeEnd),
      startTime: windowForm.startTime,
      endTime: windowForm.endTime,
      slotMinutes: windowForm.slotMinutes,
      weekdays: [1, 2, 3, 4, 5, 6, 7],
      practitionerName: windowForm.practitionerName || undefined,
      serviceCode: windowForm.serviceCode || undefined,
    });

    await loadAvailability();
  };

  const handleCreateSlot = async () => {
    if (!slotForm.startAt || !slotForm.endAt) {
      setError("Define inicio y fin del tramo.");
      return;
    }

    await staffApi.createAvailability({
      startAt: new Date(slotForm.startAt).toISOString(),
      endAt: new Date(slotForm.endAt).toISOString(),
      practitionerName: slotForm.practitionerName || undefined,
      serviceCode: slotForm.serviceCode || undefined,
    });

    setSlotForm((prev) => ({ ...prev, startAt: "", endAt: "" }));
    await loadAvailability();
  };

  const normalizeRange = (range?: DateRange) => {
    if (!range?.from) return null;
    const from = range.from;
    const to = range.to || range.from;
    return { from, to };
  };

  const handleBlockRange = async () => {
    const range = normalizeRange(selectedRange);
    if (!range) {
      setError("Selecciona un rango en el calendario.");
      return;
    }

    await staffApi.createTimeOff({
      startDate: toDateKey(range.from),
      endDate: toDateKey(range.to),
      startTime: blockForm.startTime || undefined,
      endTime: blockForm.endTime || undefined,
      reason: blockForm.reason || "Bloqueo manual",
    });

    await loadTimeOff();
  };

  const handleUnblockRange = async () => {
    const range = normalizeRange(selectedRange);
    if (!range) {
      setError("Selecciona un rango en el calendario.");
      return;
    }

    const fromKey = toDateKey(range.from);
    const toKey = toDateKey(range.to);

    const overlaps = timeOff.filter((entry) => {
      const start = `${entry.startDate}`.slice(0, 10);
      const end = `${entry.endDate}`.slice(0, 10);
      return start <= toKey && end >= fromKey;
    });

    await Promise.all(
      overlaps.map((entry) => staffApi.deleteTimeOff(entry.id)),
    );
    await loadTimeOff();
  };

  const handleDeleteSlot = async (id: string) => {
    await staffApi.deleteAvailability(id);
    await loadAvailability();
  };

  const handleCreateHoliday = async () => {
    if (!holidayForm.date) {
      setError("Selecciona una fecha de festivo.");
      return;
    }
    await staffApi.createHoliday({
      date: holidayForm.date,
      name: holidayForm.name || undefined,
    });
    setHolidayForm({ date: "", name: "" });
    await loadHolidays();
  };

  const handleDeleteHoliday = async (id: string) => {
    await staffApi.deleteHoliday(id);
    await loadHolidays();
  };

  // ===== computed =====
  const availabilityRows = useMemo(
    () =>
      availability
        .slice()
        .sort(
          (a, b) =>
            new Date(a.startAt).getTime() - new Date(b.startAt).getTime(),
        ),
    [availability],
  );

  const filteredAvailabilityRows = useMemo(() => {
    if (!dateFilter) return availabilityRows;

    return availabilityRows.filter((slot) => {
      if (!slot?.startAt) return false;
      const slotDateKey = new Date(slot.startAt).toISOString().slice(0, 10);
      return slotDateKey === dateFilter;
    });
  }, [availabilityRows, dateFilter]);

  const timeOffRows = useMemo(
    () =>
      timeOff
        .slice()
        .sort(
          (a, b) =>
            new Date(a.startDate).getTime() - new Date(b.startDate).getTime(),
        ),
    [timeOff],
  );

  const holidayRows = useMemo(
    () =>
      holidays
        .slice()
        .sort(
          (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime(),
        ),
    [holidays],
  );

  const blockedRanges = useMemo(
    () => [
      ...timeOff.map((entry) => ({
        from: new Date(entry.startDate),
        to: new Date(entry.endDate),
      })),
      ...holidays.map((entry) => ({
        from: new Date(entry.date),
        to: new Date(entry.date),
      })),
    ],
    [timeOff, holidays],
  );

  const blockedSlots = useMemo(() => {
    const map: Record<string, string[]> = {};

    availability.forEach((slot) => {
      if (slot.status !== "reserved") return;

      const date = new Date(slot.startAt).toISOString().slice(0, 10);

      const start = new Date(slot.startAt).toLocaleTimeString("es-ES", {
        hour: "2-digit",
        minute: "2-digit",
      });

      const end = new Date(slot.endAt).toLocaleTimeString("es-ES", {
        hour: "2-digit",
        minute: "2-digit",
      });

      if (!map[date]) map[date] = [];

      map[date].push(`${start} - ${end}`);
    });

    return Object.entries(map).map(([date, hours]) => ({
      date,
      hours,
    }));
  }, [availability]);

  return (
    <div className="page">
      <SectionHeader
        title="Agenda inteligente"
        subtitle="Reservas, cambios y lista de espera automática"
        action="Actualizar disponibilidad"
      />

      <section className="row g-3">
        <div className="col-md-8">
          <div className="card">
            <div className="section-title">
              <h3>Disponibilidad</h3>
              <button
                type="button"
                className="btn-ghost"
                onClick={() => setActiveInfoKey("availability")}
              >
                <IconInfo className="icon-style" />
              </button>
            </div>

            {error ? <p className="muted">{error}</p> : null}

            <p className="muted">
              Todos los días de los próximos 3 meses están disponibles por
              defecto. Selecciona un rango en el calendario para bloquear o
              desbloquear.
            </p>

            <div className="row g-3">
              <div className="col-md-5">
                <Calendar
                  selectedRange={selectedRange}
                  onSelectRange={setSelectedRange}
                  rangeStart={rangeStart}
                  rangeEnd={rangeEnd}
                  blockedRanges={blockedRanges}
                  blockedSlots={blockedSlots}
                />
              </div>

              <div className="col-md-7">
                <div className="form-field">
                  <label>Bloqueo horario (opcional)</label>
                  <div className="inline-inputs">
                    <input
                      type="time"
                      value={blockForm.startTime}
                      onChange={(event) =>
                        setBlockForm((prev) => ({
                          ...prev,
                          startTime: event.target.value,
                        }))
                      }
                    />
                    <input
                      type="time"
                      value={blockForm.endTime}
                      onChange={(event) =>
                        setBlockForm((prev) => ({
                          ...prev,
                          endTime: event.target.value,
                        }))
                      }
                    />
                  </div>
                </div>

                <div className="form-field">
                  <label>Motivo (opcional)</label>
                  <input
                    type="text"
                    value={blockForm.reason}
                    onChange={(event) =>
                      setBlockForm((prev) => ({
                        ...prev,
                        reason: event.target.value,
                      }))
                    }
                  />
                </div>

                <div className="inline-inputs mt-3">
                  <button
                    className="btn btn-secondary btn-mid"
                    onClick={handleBlockRange}
                  >
                    Bloquear rango
                  </button>
                  <button
                    className="btn btn-secondary btn-mid"
                    onClick={handleUnblockRange}
                  >
                    Desbloquear rango
                  </button>

                  <button
                    className="btn btn-secondary btn-mid"
                    onClick={handleGenerateDefault}
                  >
                    Generar disponibilidad
                  </button>
                </div>

                <div className="form-field mt-5">
                  <label>Rango de fechas</label>
                  <div className="inline-inputs">
                    <input
                      type="date"
                      value={windowForm.startDate}
                      onChange={(event) =>
                        setWindowForm((prev) => ({
                          ...prev,
                          startDate: event.target.value,
                        }))
                      }
                    />
                    <input
                      type="date"
                      value={windowForm.endDate}
                      onChange={(event) =>
                        setWindowForm((prev) => ({
                          ...prev,
                          endDate: event.target.value,
                        }))
                      }
                    />
                  </div>
                </div>

                <div className="form-field  mt-5">
                  <label>Horario diario</label>
                  <div className="inline-inputs">
                    <input
                      type="time"
                      value={windowForm.startTime}
                      onChange={(event) =>
                        setWindowForm((prev) => ({
                          ...prev,
                          startTime: event.target.value,
                        }))
                      }
                    />
                    <input
                      type="time"
                      value={windowForm.endTime}
                      onChange={(event) =>
                        setWindowForm((prev) => ({
                          ...prev,
                          endTime: event.target.value,
                        }))
                      }
                    />
                  </div>
                </div>

                <div className="form-field  mt-4">
                  <label>Duración de cita (min)</label>
                  <input
                    type="number"
                    min={5}
                    step={5}
                    value={windowForm.slotMinutes}
                    onChange={(event) =>
                      setWindowForm((prev) => ({
                        ...prev,
                        slotMinutes: Number(event.target.value) || 30,
                      }))
                    }
                  />
                </div>

                <div className="form-field  mt-5">
                  <label>Días disponibles</label>
                  <div className="inline-inputs">
                    {weekdayOptions.map((day) => (
                      <label key={day.value} className="checkbox">
                        <input
                          type="checkbox"
                          checked={windowForm.weekdays.includes(day.value)}
                          onChange={() => toggleWeekday(day.value)}
                        />
                        <span>{day.label}</span>
                      </label>
                    ))}
                  </div>
                </div>

                <div className="form-field  mt-5 mb-3">
                  <label>Profesional (opcional)</label>
                  <input
                    type="text"
                    value={windowForm.practitionerName}
                    onChange={(event) =>
                      setWindowForm((prev) => ({
                        ...prev,
                        practitionerName: event.target.value,
                      }))
                    }
                  />
                </div>

                <button
                  className="btn btn-secondary btn-mid"
                  onClick={handleOpenWindow}
                >
                  Abrir huecos
                </button>

                <div style={{ marginTop: "38px" }}>
                  <h4>Tramo puntual</h4>

                  <div className="form-field">
                    <label>Inicio</label>
                    <input
                      type="datetime-local"
                      value={slotForm.startAt}
                      onChange={(event) =>
                        setSlotForm((prev) => ({
                          ...prev,
                          startAt: event.target.value,
                        }))
                      }
                    />
                  </div>

                  <div className="form-field">
                    <label>Duración (min)</label>
                    <input
                      type="number"
                      min={5}
                      step={5}
                      value={slotForm.durationMin}
                      onChange={(event) =>
                        setSlotForm((prev) => ({
                          ...prev,
                          durationMin: Number(event.target.value) || 30,
                        }))
                      }
                    />
                  </div>

                  <div className="form-field">
                    <label>Fin</label>
                    <input
                      type="datetime-local"
                      value={slotForm.endAt}
                      onChange={(event) =>
                        setSlotForm((prev) => ({
                          ...prev,
                          endAt: event.target.value,
                        }))
                      }
                    />
                  </div>

                  <button
                    className="btn btn-secondary btn-mid mt-3"
                    onClick={handleCreateSlot}
                  >
                    Añadir tramo
                  </button>
                </div>

                {/* Ejemplo de uso de helpers de fecha en UI si lo necesitas */}
                <div style={{ marginTop: 12 }} className="muted">
                  Rango actual: {formatDate(rangeStart)} –{" "}
                  {formatDate(rangeEnd)} ({formatTime(new Date())})
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* ===== Huecos publicados ===== */}
        <div className="col-md-4">
          <div className="card">
            <div className="section-title">
              <h3>Huecos publicados</h3>
              <button
                type="button"
                className="btn-ghost"
                onClick={() => setActiveInfoKey("slots")}
              >
                <IconInfo className="icon-style" />
              </button>
            </div>

            <p className="muted mb-3">
              Vista rápida de los huecos publicados disponibles y quien los
              ocupa.
            </p>

            {loading ? (
              <p className="muted">Cargando disponibilidad...</p>
            ) : null}

            {!loading && availabilityRows.length === 0 ? (
              <p className="muted">No hay huecos registrados.</p>
            ) : null}

            {!loading &&
            availabilityRows.length > 0 &&
            filteredAvailabilityRows.length === 0 ? (
              <p className="muted">No hay huecos para la fecha seleccionada.</p>
            ) : null}

            {availabilityRows.length > 0 ? (
              <div className="slots-scroll">
                <div className="mb-3">
                  <div className="d-flex gap-2 mb-3">
                    <input
                      type="date"
                      className="form-control"
                      value={dateFilter}
                      onChange={(e) => setDateFilter(e.target.value)}
                      placeholder="Filtrar por fecha"
                    />

                    {dateFilter ? (
                      <button
                        className="btn btn-outline-secondary"
                        onClick={() => setDateFilter("")}
                      >
                        Limpiar
                      </button>
                    ) : null}
                  </div>
                </div>

                <table className="table align-top table-striped table-hover">
                  <tbody>
                    {filteredAvailabilityRows.map((slot) => (
                      <tr key={slot.id}>
                        <td width="30%">{formatSlotLabel(slot)}</td>
                        <td width="5%">{formatSlotStatus(slot)}</td>
                        <td>{formatSlotPatient(slot)}</td>
                        <td width="5%">
                          <button
                            className="btn secondary"
                            onClick={() => handleDeleteSlot(slot.id)}
                          >
                            <IconDelete className="icon-style" />
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : null}
          </div>
        </div>
      </section>

      {/* ===== Bloqueos ===== */}
      <section className="card" style={{ marginTop: "20px" }}>
        <h3>Bloqueos</h3>

        {timeOffRows.length === 0 ? (
          <p className="muted">No hay bloqueos registrados.</p>
        ) : (
          <div className="table">
            <div className="table-header">
              <span>Inicio</span>
              <span>Fin</span>
              <span>Motivo</span>
              <span>Acciones</span>
            </div>

            {timeOffRows.map((entry) => (
              <div key={entry.id} className="table-row">
                <span>
                  {entry.startAt
                    ? new Date(entry.startAt).toLocaleString("es-ES")
                    : new Date(entry.startDate).toLocaleDateString("es-ES")}
                </span>
                <span>
                  {entry.endAt
                    ? new Date(entry.endAt).toLocaleString("es-ES")
                    : new Date(entry.endDate).toLocaleDateString("es-ES")}
                </span>
                <span>{entry.reason || "Bloqueo"}</span>
                <span className="table-actions">
                  <button
                    className="btn secondary"
                    onClick={() =>
                      staffApi.deleteTimeOff(entry.id).then(loadTimeOff)
                    }
                  >
                    Eliminar
                  </button>
                </span>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* ===== Festivos ===== */}
      <section className="card" style={{ marginTop: "20px" }}>
        <h3>Festivos</h3>

        <div className="form-grid form-grid-2">
          <label className="form-field">
            Fecha
            <input
              type="date"
              value={holidayForm.date}
              onChange={(event) =>
                setHolidayForm((prev) => ({
                  ...prev,
                  date: event.target.value,
                }))
              }
            />
          </label>

          <label className="form-field">
            Motivo (opcional)
            <input
              type="text"
              value={holidayForm.name}
              onChange={(event) =>
                setHolidayForm((prev) => ({
                  ...prev,
                  name: event.target.value,
                }))
              }
              placeholder="Festivo local / vacaciones"
            />
          </label>
        </div>

        <button
          className="btn btn-secondary btn-mid"
          onClick={handleCreateHoliday}
        >
          Añadir festivo
        </button>

        {holidayRows.length === 0 ? (
          <p className="muted" style={{ marginTop: "12px" }}>
            No hay festivos registrados.
          </p>
        ) : (
          <div className="table" style={{ marginTop: "12px" }}>
            <div className="table-header">
              <span>Fecha</span>
              <span>Motivo</span>
              <span>Acciones</span>
            </div>

            {holidayRows.map((entry) => (
              <div key={entry.id} className="table-row">
                <span>{new Date(entry.date).toLocaleDateString("es-ES")}</span>
                <span>{entry.name || "Festivo"}</span>
                <span className="table-actions">
                  <button
                    className="btn secondary"
                    onClick={() => handleDeleteHoliday(entry.id)}
                  >
                    Eliminar
                  </button>
                </span>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* ===== Modal info ===== */}
      <Modal
        isOpen={Boolean(activeInfoKey)}
        title={activeInfoKey ? infoModals[activeInfoKey].title : ""}
        onClose={() => setActiveInfoKey(null)}
      >
        {activeInfoKey
          ? infoModals[activeInfoKey].paragraphs.map((text) => (
              <p key={text}>{text}</p>
            ))
          : null}

        {activeInfoKey && infoModals[activeInfoKey].bullets?.length ? (
          <ul>
            {infoModals[activeInfoKey].bullets?.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        ) : null}
      </Modal>
    </div>
  );
};
